#include "typeset_keywords.h"

namespace Hope {

namespace Typeset {

const std::string Keywords::NONE = "";

const std::unordered_map<std::string_view, std::string> Keywords::map{
    {"0", "𝟘"},
    {"1", "𝟙"},
    {"2", "𝟚"},
    {"3", "𝟛"},
    {"4", "𝟜"},
    {"5", "𝟝"},
    {"6", "𝟞"},
    {"7", "𝟟"},
    {"8", "𝟠"},
    {"9", "𝟡"},
    {"|", "‖"},
    {"adots", "⋰"},
    {"aleph", "ℵ"},
    {"alpha", "α"},
    {"Alpha", "Α"},
    {"angle", "∠"},
    {"approx", "≈"},
    {"ast", "∗"},
    {"B", "𝔹"},
    {"bagmember", "⋿"},
    {"because", "∵"},
    {"beta", "β"},
    {"Beta", "Β"},
    {"beth", "ℶ"},
    {"bot", "⊥"},
    {"bowtie", "⋈"},
    {"box", "□"},
    {"bumpeq", "≏"},
    {"C", "ℂ"},
    {"cap", "∩"},
    {"cdot", "⋅"},
    {"cdots", "⋯"},
    {"cent", "¢"},
    {"ceqdef", "≔"},
    {"checkmark", "✓"},
    {"chi", "χ"},
    {"Chi", "Χ"},
    {"circ", "∘"},
    {"Colon", "∷"},
    {"complement", "∁"},
    {"cong", "≅"},
    {"copyright", "©"},
    {"cup", "∪"},
    {"cupdot", "⊍"},
    {"d", "ⅆ"},
    {"D", "𝔻"},
    {"dagger", "†"},
    {"daleth", "ℸ "},
    {"ddagger", "‡"},
    {"ddots", "⋱"},
    {"delta", "δ"},
    {"Delta", "Δ"},
    {"diameter", "⌀"},
    {"digamma", "ϝ"},
    {"Digamma", "Ϝ"},
    {"div", "÷"},
    {"doteq", "≐"},
    {"downarrow", "↓"},
    {"e", "ℯ"},
    {"E", "𝔼"},
    {"eightnote", "♪"},
    {"emptyset", "∅"},
    {"epsilon", "ϵ"},
    {"Epsilon", "Ε"},
    {"eqcolon", "∹"},
    {"eqdef", "≝"},
    {"equiv", "≡"},
    {"Equiv", "≣"},
    {"errbar", "⧮"},
    {"eta", "η"},
    {"Eta", "Η"},
    {"Euler", "ℇ"},
    {"euro", "€"},
    {"Exclam", "‼"},
    {"exists", "∃"},
    {"F", "𝔽"},
    {"flat", "♭"},
    {"forall", "∀"},
    {"fourth", "⁗"},
    {"frownie", "☹"},
    {"gamma", "γ"},
    {"Gamma", "Γ"},
    {"geq", "≥"},
    {"geqq", "≧"},
    {"gg", "≫"},
    {"ggg", "⋙"},
    {"gimel", "ℷ"},
    {"H", "ℍ"},
    {"ham", "ℋ"},
    {"Im", "ℑ"},
    {"imath", "ⅈ"},
    {"implies", "⇒"},
    {"in", "∈"},
    {"incr", "∆"},
    {"infty", "∞"},
    {"iota", "ι"},
    {"Iota", "Ι"},
    {"J", "𝕁"},
    {"jmath", "ⅉ"},
    {"kappa", "κ"},
    {"Kappa", "Κ"},
    {"lag", "ℒ"},
    {"lambda", "λ"},
    {"Lambda", "Λ"},
    {"land", "∧"},
    {"langle", "⟨"},
    {"lceil", "⌈"},
    {"leftarrow", "←"},
    {"Leftarrow", "⇐"},
    {"leftrightarrow", "↔"},
    {"Leftrightarrow", "⇔"},
    {"leq", "≤"},
    {"leqq", "≦"},
    {"lfloor", "⌊"},
    {"ll", "≪"},
    {"llangle", "⟪"},
    {"llbracket", "⟦"},
    {"lll", "⋘"},
    {"lor", "∨"},
    {"ltimes", "⋉"},
    {"maltese", "✠"},
    {"mapsto", "↦"},
    {"mathsterling", "£"},
    {"mathyen", "¥"},
    {"measuredangle", "∡"},
    {"mho", "℧"},
    {"mp", "∓"},
    {"mu", "μ"},
    {"Mu", "Μ"},
    {"N", "ℕ"},
    {"nabla", "∇"},
    {"napprox", "≉"},
    {"natural", "♮"},
    {"ncong", "≇"},
    {"ne", "≠"},
    {"neg", "¬"},
    {"neq", "≠"},
    {"nequiv", "≢"},
    {"nexists", "∄"},
    {"ngtr", "≯"},
    {"ni", "∋"},
    {"nless", "≮"},
    {"nmid", "∤"},
    {"nni", "∌"},
    {"notin", "∉"},
    {"nsubset", "⊄"},
    {"nsubseteq", "⊈"},
    {"nsupset", "⊅"},
    {"nsupseteq", "⊉"},
    {"nu", "ν"},
    {"Nu", "Ν"},
    {"O", "𝕆"},
    {"odot", "⨀"},
    {"omega", "ω"},
    {"Omega", "Ω"},
    {"omicron", "ο"},
    {"Omicron", "Ο"},
    {"ominus", "⊖"},
    {"oplus", "⊕"},
    {"oslash", "⊘"},
    {"otimes", "⊗"},
    {"P", "ℙ"},
    {"partial", "∂"},
    {"perp", "⊥"},
    {"phi", "ϕ"},
    {"Phi", "Φ"},
    {"pi", "π"},
    {"Pi", "Π"},
    {"Planckconst", "ℎ"},
    {"pm", "±"},
    {"prec", "≺"},
    {"prime", "′"},
    {"propto", "∝"},
    {"psi", "ψ"},
    {"Psi", "Ψ"},
    {"Q", "ℚ"},
    {"QED", "■"},
    {"qoppa", "ϙ"},
    {"Qoppa", "Ϙ"},
    {"quarternote", "♩"},
    {"questeq", "≟"},
    {"R", "ℝ"},
    {"rangle", "⟩"},
    {"rceil", "⌉"},
    {"Re", "ℜ"},
    {"registered", "®"},
    {"rfloor", "⌋"},
    {"rho", "ρ"},
    {"Rho", "Ρ"},
    {"rightangle", "∟"},
    {"rightarrow", "→"},
    {"Rightarrow", "⇒"},
    {"rightleftarrows", "⇄"},
    {"rrangle", "⟫"},
    {"rrbracket", "⟧"},
    {"rtimes", "⋊"},
    {"S", "𝕊"},
    {"second", "″"},
    {"sharp", "♯"},
    {"shuffle", "⧢"},
    {"sigma", "σ"},
    {"Sigma", "Σ"},
    {"sinewave", "∿"},
    {"sphericalangle", "∢"},
    {"sqcap", "⊓"},
    {"sqcup", "⊔"},
    {"sqsubset", "⊏"},
    {"sqsubseteq", "⊑"},
    {"sqsupset", "⊐"},
    {"sqsupseteq", "⊒"},
    {"subset", "⊂"},
    {"Subset", "⋐"},
    {"subsetcirc", "⟃"},
    {"subseteq", "⊆"},
    {"succ", "≻"},
    {"supset", "⊃"},
    {"supsetcirc", "⟄"},
    {"supseteq", "⊇"},
    {"T", "𝕋"},
    {"tau", "τ"},
    {"Tau", "Τ"},
    {"therefore", "∴"},
    {"thermod", "⧧"},
    {"theta", "θ"},
    {"Theta", "Θ"},
    {"third", "‴"},
    {"times", "×"},
    {"to", "→"},
    {"top", "⊤"},
    {"triangleleft", "◅"},
    {"triangleq", "≜"},
    {"triangleright", "▻"},
    {"twonotes", "♫"},
    {"U", "𝕌"},
    {"uparrow", "↑"},
    {"updownarrow", "↕"},
    {"uplus", "⊎"},
    {"upsilon", "υ"},
    {"Upsilon", "Υ"},
    {"varepsilon", "ε"},
    {"varkappa", "ϰ"},
    {"varphi", "φ"},
    {"varpi", "ϖ"},
    {"varrho", "ϱ"},
    {"varsigma", "ς"},
    {"vartheta", "ϑ"},
    {"varTheta", "ϴ"},
    {"vdash", "⊢"},
    {"vDash", "⊧"},
    {"vdots", "⋮"},
    {"vee", "∨"},
    {"veebar", "⊻"},
    {"warning", "⚠"},
    {"wedge", "∧"},
    {"wp", "℘"},
    {"wr", "≀"},
    {"xi", "ξ"},
    {"Xi", "Ξ"},
    {"Z", "ℤ"},
    {"Zbar", "Ƶ"},
    {"zeta", "ζ"},
    {"Zeta", "Ζ"},
    {"mat", Keywords::con(MATRIX, 9, {3, 3})},
    {"cases", Keywords::con(CASES, 4, {2})},
    {"^_", Keywords::con(DUALSCRIPT, 2, {})},
    {"frac", Keywords::con(FRACTION, 2, {})},
    {"binom", Keywords::con(BINOMIAL, 2, {})},
    {"lim", Keywords::con(LIMIT, 2, {})},
    {"nrt", Keywords::con(NRT, 2, {})},
    {"sum2", Keywords::con(BIGSUM2, 2, {})},
    {"prod2", Keywords::con(BIGPROD2, 2, {})},
    {"coprod2", Keywords::con(BIGCOPROD2, 2, {})},
    {"union2", Keywords::con(BIGUNION2, 2, {})},
    {"intersection2", Keywords::con(BIGINTERSECTION2, 2, {})},
    {"int2", Keywords::con(INTEGRAL2, 2, {})},
    {"oint2", Keywords::con(INTEGRALCONV2, 2, {})},
    {"^", Keywords::con(SUPERSCRIPT, 1, {})},
    {"_", Keywords::con(SUBSCRIPT, 1, {})},
    {"max", Keywords::con(MAX, 1, {})},
    {"min", Keywords::con(MIN, 1, {})},
    {"inf", Keywords::con(INF, 1, {})},
    {"sup", Keywords::con(SUP, 1, {})},
    {"sqrt", Keywords::con(SQRT, 1, {})},
    {"sum1", Keywords::con(BIGSUM1, 1, {})},
    {"prod1", Keywords::con(BIGPROD1, 1, {})},
    {"coprod1", Keywords::con(BIGCOPROD1, 1, {})},
    {"union1", Keywords::con(BIGUNION1, 1, {})},
    {"intersection1", Keywords::con(BIGINTERSECTION1, 1, {})},
    {"int1", Keywords::con(INTEGRAL1, 1, {})},
    {"iint1", Keywords::con(DOUBLEINTEGRAL1, 1, {})},
    {"iiint1", Keywords::con(TRIPLEINTEGRAL1, 1, {})},
    {"oint1", Keywords::con(INTEGRALCONV1, 1, {})},
    {"oiint1", Keywords::con(DOUBLEINTEGRALCONV1, 1, {})},
    {"oiiint1", Keywords::con(TRIPLEINTEGRALCONV1, 1, {})},
    {"sum", Keywords::con(BIGSUM0, 0, {})},
    {"prod", Keywords::con(BIGPROD0, 0, {})},
    {"coprod", Keywords::con(BIGCOPROD0, 0, {})},
    {"union", Keywords::con(BIGUNION0, 0, {})},
    {"intersection", Keywords::con(BIGINTERSECTION0, 0, {})},
    {"int", Keywords::con(INTEGRAL0, 0, {})},
    {"iint", Keywords::con(DOUBLEINTEGRAL0, 0, {})},
    {"iiint", Keywords::con(TRIPLEINTEGRAL0, 0, {})},
    {"oint", Keywords::con(INTEGRALCONV0, 0, {})},
    {"oiint", Keywords::con(DOUBLEINTEGRALCONV0, 0, {})},
    {"oiiint", Keywords::con(TRIPLEINTEGRALCONV0, 0, {})},
    {"hat", Keywords::con(ACCENTHAT, 1, {})},
    {"tilde", Keywords::con(ACCENTTILDE, 1, {})},
    {"bar", Keywords::con(ACCENTBAR, 1, {})},
    {"breve", Keywords::con(ACCENTBREVE, 1, {})},
    {"dot", Keywords::con(ACCENTDOT, 1, {})},
    {"ddot", Keywords::con(ACCENTDDOT, 1, {})},
    {"dddot", Keywords::con(ACCENTDDDOT, 1, {})},
};

}

}

