name: Forscape App Compiles And Runs (ubuntu-latest gcc)
on: push
#DO THIS: change back
#on:
#  pull_request:
#  push:
#    branches: main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: Qt
        uses: jurplel/install-qt-action@v3
      - uses: actions/checkout@v3
      - id: install_conan
        uses: turtlebrowser/get-conan@main
      - id: patch_conan
        run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - id: run_conan
        run: cd ${GITHUB_WORKSPACE}/app && conan install --generator cmake_find_package --install-folder ../build/conan-dependencies .
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/app && cmake -B../build -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/build && make
      - id: launch_fresh
        run: cd ${GITHUB_WORKSPACE}/build && timeout 5 ./Forscape -platform offscreen && test $? -eq 124
      - id: launch_with_file
        run: cd ${GITHUB_WORKSPACE}/build && timeout 5 ./Forscape ../test/interpreter_scripts/in/root_finding_terse.Ï€ -platform offscreen && test $? -eq 124
      - id: launch_with_cache
        run: cd ${GITHUB_WORKSPACE}/build && timeout 5 ./Forscape -platform offscreen && test $? -eq 124