name: Forscape App Compiles And Runs (ubuntu-latest gcc)
on:
  pull_request:
  push:
    branches: main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: Qt
        uses: jurplel/install-qt-action@v3
      - uses: actions/checkout@v3
      - id: install_conan
        uses: turtlebrowser/get-conan@main
      - id: patch_conan
        run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - id: run_conan
        run: cd ${GITHUB_WORKSPACE}/app && conan install --generator cmake_find_package --install-folder ../build/conan-dependencies .
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/app && cmake -B../build -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/build && make
      - id: launch
        run: cd ${GITHUB_WORKSPACE}/build && ${GITHUB_WORKSPACE}/.github/workflows/app_run_and_check_exit_code.sh