name: C++ Integration Tests (Ubuntu gcc 32-bit)
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/test && export CXXFLAGS=-m32 && cmake -B../build_test -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/build_test && make
      - id: run
        run: cd ${GITHUB_WORKSPACE}/build_test && ./HopeTests
