name: C++ Integration Tests (windows-latest msbuild)
on: push
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: cmake
        run: cd $Env:GITHUB_WORKSPACE/test && cmake -B../build_test -S.
      - id: msbuild
        run: cd $Env:GITHUB_WORKSPACE/build_test && msbuild
      - id: run
        run: cd $Env:GITHUB_WORKSPACE/build_test && ./HopeTests
