name: C++ Integration Tests (ubuntu-latest gcc 32-bit)
on:
  pull_request:
  push:
    branches: main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: support_32bit
        run: sudo apt-get install gcc-multilib g++-multilib
      - id: install_conan
        uses: turtlebrowser/get-conan@main
      - id: patch_conan
        run: conan profile detect --name default
      - id: run_conan
        run: cd ${GITHUB_WORKSPACE}/test &&
             export CFLAGS=-m32 &&
             export CXXFLAGS=-m32 &&
             export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig &&
             conan install -e CXXFLAGS=-m32 --generator cmake_find_package --output-folder ../build_test/conan-dependencies .
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/test &&
             export CFLAGS=-m32 &&
             export CXXFLAGS=-m32 &&
             export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig &&
             cmake -B../build_test -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/build_test && make
      - id: run
        run: cd ${GITHUB_WORKSPACE}/build_test && ./ForscapeTests
