name: C++ Integration Tests (windows-latest msbuild)
on:
  pull_request:
  push:
    branches: main
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - id: install_conan
        uses: turtlebrowser/get-conan@main
      - id: run_conan
        run: cd $Env:GITHUB_WORKSPACE/test && conan install --generator cmake_find_package --install-folder ../build_test/conan-dependencies .
      - id: cmake
        run: cd $Env:GITHUB_WORKSPACE/test && cmake -B../build_test -S.
      - name: Build app for release
        run: cd $Env:GITHUB_WORKSPACE/build_test && msbuild HopeTests.vcxproj -property:Configuration=Debug
      - id: run
        run: cd $Env:GITHUB_WORKSPACE/build_test && ./HopeTests.exe
