name: C++ Integration Tests (ubuntu-latest gcc 32-bit)
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: support_32bit
        run: apt-get install gcc-multilib g++-multilib
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/test &&
             export CFLAGS=-m32 &&
             export CXXFLAGS=-m32 &&
             export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig &&
             cmake -B../build_test -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/build_test && make
      - id: run
        run: cd ${GITHUB_WORKSPACE}/build_test && ./HopeTests
