name: C++ Integration Tests (windows-latest)
on: push
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: cmake
        run: cd $Env:GITHUB_WORKSPACE/test && cmake -B../build_test -S.
      - id: make
        run: cd $Env:GITHUB_WORKSPACE/build_test && pwd && ls && mingw32-make -f makefile.txt
      - id: run
        run: cd $Env:GITHUB_WORKSPACE/build_test && ./HopeTests
