name: DO_THIS check
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: permissions
        run: chmod +x "${GITHUB_WORKSPACE}/.github/do_this_check.sh"
      - id: check
        run: ${GITHUB_WORKSPACE}/.github/do_this_check.sh
