name: Qt Integration Tests
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: Qt
        # uses: jurplel/install-qt-action@v2
        # with:
        #  modules: qtsvg
        run: sudo apt-get install qt5-default libqt5svg5-dev '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
      - uses: actions/checkout@v2
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/test && cmake -DTEST_QT=ON -B../build_test -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/build_test && make
      - id: run
        run: cd ${GITHUB_WORKSPACE}/build_test && ./HopeTests
