name: Qt Integration Tests
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
        uses: jurplel/install-qt-action@v2
        version: 5.14.2 #Havin' an issue with Qt working
        with:
          modules: qtsvg
      - uses: actions/checkout@v2
      - id: cmake
        run: cd ${GITHUB_WORKSPACE}/test && cmake -DTEST_QT=ON -B../build_test -S.
      - id: make
        run: cd ${GITHUB_WORKSPACE}/build_test && make
      - id: run
        run: cd ${GITHUB_WORKSPACE}/build_test && ./HopeTests
