name: C++ Integration Tests
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: build
        run:
          cd test
          cmake -B../build_test -S.
          cd ../build_test
          make
      - id: run
        run: ./HopeTests
